---
output: html_fragment
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

<!-- ```{=html} -->
<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { -->
<!--     extensions: ["[Contrib]/mhchem/mhchem.js"] -->
<!-- } -->
<!-- }); -->
<!-- MathJax.Hub.Config({  -->
<!--         "HTML-CSS": { scale: 90 },  -->
<!--         SVG: { linebreaks: { automatic:true } },  -->
<!--  }); -->
<!-- </script> -->
<!-- ``` -->

<!-- text for introduction -->

The Fourier transform (FT) is a mathematical operation that allows us to take a signal recorded in one measurement domain (perhaps time) and convert it into a complementary signal in another measurement domain (perhaps frequency).

#### Time Domains and Frequency Domains

The figure on the upper right is a square wave with amplitude shown on the *y*-axis and time shown on the *x*-axis. The square wave has a period of 1 sec, a frequency of 1 sec^-1^, and an amplitude that varies between $\pm 1$. The figure shows two full periods and continues in both directions along the *x*-axis. This is the time domain representation of a square wave. 

The middle figure shows the same square wave expressed as a series of sine waves, called a Fourier series. Each vertical line defines a sine wave by its amplitude, which are the heights of the vertical lines (shown above each line), and by its frequency, which are the positions of the vertical lines along the *x*-axis. The figure shows the first 10 sine waves of an infinite series defined as 
$$y(t) = \frac{4}{\pi} \sum_{k = 1}^{5} \frac{1}{2k-1} sin \left( 2\pi(2k-1)t \right)$$
where $k$ is an index for the sine wave $(k = 1, 2, 3, \dots \infty)$. The first sine wave, for example, has an amplitude, $A_1$, of 1.273 and a frequency, $f_1$, of 1; each subsequent sine wave has an amplitude equal to $\frac{A_1}{2k-1}$ and a frequency equal to $f_1 \times (2k-1)$. This is the frequency domain representation of the square wave shown on the upper right.

#### Moving Between Domains

Although the figure on the top right clearly is a square wave, it isn't obvious that the series of amplitudes and frequencies in the middle figure is equivalent to the square wave. The figure on the lower right shows the first five sine waves in this Fourier series as dashed lines. The sum of these five sine waves is the solid, sky-blue line. Although five sine waves is not sufficient to reproduce exactly the square wave shown by the black, dashed line, including more sine waves will provide a better approximation.
