---
output: html_fragment
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

<!-- ```{=html} -->
<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { -->
<!--     extensions: ["[Contrib]/mhchem/mhchem.js"] -->
<!-- } -->
<!-- }); -->
<!-- MathJax.Hub.Config({  -->
<!--         "HTML-CSS": { scale: 90 },  -->
<!--         SVG: { linebreaks: { automatic:true } },  -->
<!--  }); -->
<!-- </script> -->
<!-- ``` -->

<!-- text for activity 2 -->

A single peak in the frequency domain corresponds to a single damped oscillating wave in the time domain. If there are two peaks in the frequency domain, then the time domain signal should show evidence of both peaks. You can use the controls on the right to explore the relationship between two Gaussian peaks in the frequency domain and their corresponding contributions to the time domain signal. By default, both peaks are included in the frequency domain spectrum and in the time domain spectrum; you may, however, use the radio buttons to isolate the individual peaks and their individual time domain signals.

**Exercise 1.** The default inputs create two peaks with identical widths and areas with the first peak centered at a frequency of 40 and the second peak centered at a frequency of 60. Examine the time domain spectrum and explain how its pattern is similar to and different from that for a system with a single peak with a frequency of 40 or of 60.  

**Exercise 2.** Make a prediction for what you will see in the frequency domain and in the time domain if a system has two peaks with the same position (50), the same width (10), and the same area (10). Adjust the sliders to create this system and then evaluate your prediction.

**Exercise 3.** Adjust the sliders so that peak one has a position of 40, a width of 5, and an area of 10, and so that peak two has a position of 60, a width of 5, and an area of 10. Predict how the time domain spectrum will change if you adjust both peaks to a width of 10 and then evaluate your prediction.

**Exercise 4.** Adjust the sliders for peak 1 to a position of 40, a width of 5, and an area of 10, and adjust the sliders for peak 2 to a position of 50, a width of 5, and an area of 10. Working in steps of +1 or +2 along the frequency axis, adjust the position for peak 1 from 40 to 60 and describe how the time domain spectrum changes.

**Exercise 5.** Although the controls allow for only two peaks in the frequency domain, what do you think the time domain spectrum will look like if there are many more peaks in the frequency domain?
