---
output: html_fragment
---

<!-- The following script makes it possible to use the mhchem -->
<!-- latex package in a .Rmd file and to knit it into an .html file -->
<!-- the font size is scaled to 90% to match text -->

<!-- ```{=html} -->
<!-- <script type="text/x-mathjax-config"> -->
<!-- MathJax.Hub.Config({ -->
<!--   TeX: { -->
<!--     extensions: ["[Contrib]/mhchem/mhchem.js"] -->
<!-- } -->
<!-- }); -->
<!-- MathJax.Hub.Config({  -->
<!--         "HTML-CSS": { scale: 90 },  -->
<!--         SVG: { linebreaks: { automatic:true } },  -->
<!--  }); -->
<!-- </script> -->
<!-- ``` -->

<!-- text for wrapping up -->

#### FT of Diffuse Reflectance Spectrum

Our treatment of Fourier transforms in this module is limited to a system with just one or two ideal peaks as this allowed us to explore the relationship between a peak's position in the frequency domain and its oscillation period in the time domain, a peak's width in the frequency domain and its decay rate in the time domain, and a peak's area in the frequency domain and its intensity in the time domain. A more complex spectrum---one with multiple peaks in the frequency domain---results in a more complex pattern of oscillating waves in the time domain. The figure on the upper right, for example, shows a portion of the diffuse reflectance infrared spectrum for urea and, on the lower right, a portion of its time domain spectrum following a Fourier transform.

#### Time Domains and Frequency Domains

In the figure on the right---and in the examples considered in this module---the frequency domain is a set of non-periodic peaks and the time domain is an oscillating signal whose amplitude decays over time. For the diffuse reflectance spectra seen on the right, collected using a Fourier Transform Infrared Spectrometer (FT--IR), the measured signal is the time domain spectrum on the lower right, which is then converted into the frequency domain spectrum by applying the Fourier transform. For other analytical methods, the peaks appear in the time domain and the corresponding frequency domain is obtained by applying the Fourier transform. 

#### Data Set Used in this Module

The data for the urea's diffuse reflectance spectrum is from the [National Institute of Standards and Technology (NIST)](https://webbook.nist.gov/cgi/cbook.cgi?ID=C57136&Type=IR-SPEC&Index=1#IR-SPEC). The original data gives the intensity of reflected light for 7135 wavenumbers from approximately 7500 cm^--1^ to 600 cm^--1^, and stored in JCAMP-DX format with an extension of .jdx (JCAMP is the Joint Committee on Atomic and Molecular Physical Data). The data was extracted from the .jdx file using the `R` package `readJDX`, trimmed to 4096 points from approximately 4550 cm^--1^ to approximately 600 ^--1^, and stored in .csv format. The Fourier transformation of the data used `R`'s `fft()` function. (*Why 4096 points? The mathematics behind the Fourier transform requires that the number of data points be a power of 2; 4096 is equivalent to $2^{12}$*)

Gaussian peaks in the frequency domain were created in `R` using the `dnorm()` function 
$$\text{intensity = area} \times \text{dnorm(x, position, width/2.35)}$$
where area, position, and width are the values set by the slider inputs, where *x* is a vector of frequencies, and where width is divided by 2.35 to convert the width at half height to a standard deviation.

Lorentzian peaks in the frequency domain were created in `R` using the code
$$\text{intensity = area} \times \frac{1}{\pi} \times \frac{0.5 \times \text{width}}{(\text{x}-\text{position})^2 + (0.5 \times \text{width})^2}$$
where area, position, and width are the values set by the slider inputs, and where *x* is a vector of frequencies.

The Voigt peaks for a given area, position, and width are approximated as a 50:50 mixture of the corresponding Gaussian and Lorentzian peaks.

#### Additional Resources

The following series of papers provide a good introduction to the Fourier transform:

* Glasser, L. [“Fourier Transforms for Chemists: Part I. Introduction to the Fourier Transform](https://doi.org/10.1021/ed064pA228),” J. Chem. Educ. 1987, 64, A228–A233
* Glasser, L. [“Fourier Transforms for Chemists: Part II. Fourier Transforms in Chemistry and Spectroscopy](https://doi.org/10.1021/ed064pA260),” J. Chem. Educ. 1987, 64, A260–A266
* Glasser, L. [“Fourier Transforms for Chemists: Part III. Fourier Transforms in Data Treatment](https://doi.org/10.1021/ed064pA306),” J. Chem. Educ. 1987, 64, A306–A313.

The following three texts provide additional insight into the Fourier transform and some of the mathematical details; the first of the three texts is the most basic and the last of the three texts is more advanced:

* Kenneth R. Beebe, Randy J. Pell, Mary Beth Seaholtz [*Chemometrics: A Practical Guide*, Wiley-Interscience, NY, 1998](https://www.wiley.com/en-us/Chemometrics%3A+A+Practical+Guide-p-9780471124511).
* Richard G. Brereton [*Chemometrics: Data Analysis for the Laboratory and Chemical Plant*, Wiley, Chichester, UK 2003.](https://onlinelibrary.wiley.com/doi/book/10.1002/0470863242)
* B.G.M. Vandegubste, D. L. Massart, L.M.C. Buydens, S. De Jong, P.J. Lewi, J. Smeyers-Verbeke Chapter 40 in [*Handbook of Chemometrics and Qualimetrics: Part B,, Elsevier, Amsterdam, 1998.](https://shop.elsevier.com/books/handbook-of-chemometrics-and-qualimetrics/massart/978-0-444-82853-8)

For additional information about the superposition of waves, see AC3.0: Superposition of Waves from this series of modules on analytical chemistry.

Additional browser-based applications on the Fourier transform are available [here](http://195.134.76.37/applets/AppletFourier/Appl_Fourier2.html) and [here](http://195.134.76.37/applets/AppletFourAnal/Appl_FourAnal2.html).
